### ISSUE TITLE
Data model export as graphml file -> import and edit graphml file using yEd Editor

### ISSUE THREAD

**Issue by jarasch** [covidgraph/documentation#75] opened 2020-07-22 12:16 UTC
We had the idea to generate the data model using graphml export from neo4j and edit the model in yEd
having nice graphics and grouping function. 
@Jiros played around with fixing the file and we have one version which works
Link to two graphml files attached. 

### Export query in neo4j
```cypher
call apoc.meta.graph() yield nodes, relationships
With 
([x in nodes where apoc.any.properties(x).name in ['Abstract', 'AbstractCollection', 'Affiliation', 'AgeGroup', 'Author', 'AuthorCollection', 'BodyText', 'BodyTextCollection', 'Citation', 'City', 'ClinicalTrial', 'Country', 'DailyReport', 'Entity', 'ExclusionCriteria', 'Facility', 'GOTerm', 'Gene', 'GeneSymbol', 'GtexDetailedTissue', 'GtexTissue', 'InclusionCriteria', 'Location', 'Paper', 'Patent', 'PatentAbstract', 'PatentClaim', 'PatentDescription', 'PatentLiteratureCitation', 'PatentNumber', 'PatentTitle', 'Pathway', 'Phase', 'Protein', 'Province', 'Reference', 'ReferenceCollection', 'Transcript','Fragment']]) As things,
([x in relationships where not type(x) in ['INVENTOR', 'LOCATED_IN']]) as rels

CALL apoc.export.graphml.data(things,rels, "export.graphml", {})
YIELD file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
RETURN file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
```
### export file which causes import exception:
https://cloud.connect.dzd-ev.de/s/yPf2Gj8DwC6s5By

Export works fine - thanks to @sarmbruster 

When loading it into yEd we get the following exception:

### Exception upon import into yEd

y.H.B.B.a: Source node id n-53 not defined in this graph!
	at y.H.B.B.Y.Ă(Unknown Source)
	at y.H.B.B.Y.ā(Unknown Source)
	at y.H.B.B.Y.Ć(Unknown Source)
	at y.H.B.B.Y.ā(Unknown Source)
	at y.H.B.B.Y.Ą(Unknown Source)
	at y.H.B.B.Y.ā(Unknown Source)
	at y.H.B.B._.ā(Unknown Source)
	at y.H.B.A$14.ā(Unknown Source)
	at y.H.B.A.ā(Unknown Source)
	at y.H.B.A.ā(Unknown Source)
	at y.H.Q.ā(Unknown Source)
	at com.yworks.A.B.G.A.U$H.Ă(Unknown Source)
	at com.yworks.A.B.G.A.U$H.ā(Unknown Source)
	at com.yworks.A.B.G.A.U.ā(Unknown Source)
	at com.yworks.A.B.G.A.Q.ā(Unknown Source)
	at y.H.G.ā(Unknown Source)
	at y.B.A.M.Đ(Unknown Source)
	at y.B.h.č(Unknown Source)
	at y.B.h.ā(Unknown Source)
	at y.B.h.ă(Unknown Source)
	at com.yworks.A.B.Z.ă(Unknown Source)
	at com.yworks.A.B.Z.ā(Unknown Source)
	at com.yworks.A.J.P.ā(Unknown Source)
	at com.yworks.A.J.P.ā(Unknown Source)
	at com.yworks.A.J.P$A.Ă(Unknown Source)
	at com.yworks.A.J.P.ā(Unknown Source)
	at com.yworks.A.K.D.ā(Unknown Source)
	at com.yworks.A.K.j.actionPerformed(Unknown Source)
	at com.yworks.A.D.d$A.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:349)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:975)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at java.desktop/javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
	at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:297)
	at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2993)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2985)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### file which works:
https://cloud.connect.dzd-ev.de/s/gEc5msadkNim2sD

**Comment by yGuy** [comment] 2020-07-22 12:51
Isn't that a duplicate of https://github.com/covidgraph/steering-group/issues/17#issuecomment-658187904 ?

I wrote:

That's because the query dumps all relationships, no matter whether the nodes for them are dumped, too. In this case the relationship is "PATENTFAMILY_HAS_LENSID" and it obviously starts from a PATENTFAMILY which is not included in the nodes to export. So you would have to either exclude PATENTFAMILY_HAS_LENSID or include patent family.
But if you do that, the next errors show up.
Maybe @sarmbruster can enhance the query so that only relationships are exported for which the nodes are also exported? Otherwise the graphml file will be invalid.

I manually fixed the file I got from @jarasch - you can view it here: https://www.yworks.com/yed-live/?file=https://gist.githubusercontent.com/yGuy/547c23d6a2300fb71d9633b13503b657/raw/85127f67423d8f35f7643ec843094e8027041439/exported-fixed-and-property-mapped

**Comment by Jiros** [comment] 2020-07-22 13:10
@sarmbruster For context, this is the sort of end goal I'm aiming for and anything that can help as a shortcut to getting there when we add new data sources etc would be great - https://github.com/covidgraph/documentation/blob/master/diagrams/Schema%20v0.1.png

@yGuy - yes, this is duplicate but the original is in a private repo so can't be assigned to people outside of the repo or transferred from a private to a public repo (as far as I know anyway...)

**Comment by sarmbruster** [comment] 2020-07-23 09:31
Thanks @yGuy for the analysis. Please find below a modified queries that filters out relationships whose start or end node is not in the list of nodes. That should do the trick. Can someone please test this?

```
call apoc.meta.graph() yield nodes, relationships
With 
([x in nodes where apoc.any.properties(x).name in ['Abstract', 'AbstractCollection', 'Affiliation', 'AgeGroup', 'Author', 'AuthorCollection', 'BodyText', 'BodyTextCollection', 'Citation', 'City', 'ClinicalTrial', 'Country', 'DailyReport', 'Entity', 'ExclusionCriteria', 'Facility', 'GOTerm', 'Gene', 'GeneSymbol', 'GtexDetailedTissue', 'GtexTissue', 'InclusionCriteria', 'Location', 'Paper', 'Patent', 'PatentAbstract', 'PatentClaim', 'PatentDescription', 'PatentLiteratureCitation', 'PatentNumber', 'PatentTitle', 'Pathway', 'Phase', 'Protein', 'Province', 'Reference', 'ReferenceCollection', 'Transcript','Fragment']]) As things, relationships
with things, [x in things|id(x)] as thingsIds, relationships
with things, ([x in relationships where not type(x) in ['INVENTOR', 'LOCATED_IN'] and id(startNode(x)) in thingsIds and id(endNode(x)) in thingsIds]) as rels
CALL apoc.export.graphml.data(things,rels, "export.graphml", {})
YIELD file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
RETURN file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
```

**Comment by yGuy** [comment] 2020-07-23 14:10
I was not able to verify this, since the call did not return for several hours, now :-/   
Maybe @motey needs to run this somewhere more closer to the metal? The neo4j browser did not work for me, so far on prod.

**Comment by motey** [comment] 2020-07-23 14:36
started the call in the container in cypher-shell. can not get closer :) will update you here if something interesting happens....

**Comment by sarmbruster** [comment] 2020-07-23 15:20
if you use `apoc.meta.graphSample()` instead of `apoc.meta.graph()` it should work almost instantly. However it works based on sampling and not on a full scan.


```call apoc.meta.graphSample() yield nodes, relationships
With 
([x in nodes where apoc.any.properties(x).name in ['Abstract', 'AbstractCollection', 'Affiliation', 'AgeGroup', 'Author', 'AuthorCollection', 'BodyText', 'BodyTextCollection', 'Citation', 'City', 'ClinicalTrial', 'Country', 'DailyReport', 'Entity', 'ExclusionCriteria', 'Facility', 'GOTerm', 'Gene', 'GeneSymbol', 'GtexDetailedTissue', 'GtexTissue', 'InclusionCriteria', 'Location', 'Paper', 'Patent', 'PatentAbstract', 'PatentClaim', 'PatentDescription', 'PatentLiteratureCitation', 'PatentNumber', 'PatentTitle', 'Pathway', 'Phase', 'Protein', 'Province', 'Reference', 'ReferenceCollection', 'Transcript','Fragment']]) As things, relationships
with things, [x in things|id(x)] as thingsIds, relationships
with things, ([x in relationships where not type(x) in ['INVENTOR', 'LOCATED_IN'] and id(startNode(x)) in thingsIds and id(endNode(x)) in thingsIds]) as rels
CALL apoc.export.graphml.data(things,rels, "export.graphml", {})
YIELD file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
RETURN file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data```

**Comment by motey** [comment] 2020-07-24 07:07
```
neo4j> call apoc.meta.graph() yield nodes, relationships
       With 
       ([x in nodes where apoc.any.properties(x).name in ['Abstract', 'AbstractCollection', 'Affiliation', 'AgeGroup', 'Author', 'AuthorCollection', 'BodyText', 'BodyTextCollection', 'Citation', 'City', 'ClinicalTrial', 'Country', 'DailyReport', 'Entity', 'ExclusionCriteria', 'Facility', 'GOTerm', 'Gene', 'GeneSymbol', 'GtexDetailedTissue', 'GtexTissue', 'InclusionCriteria', 'Location', 'Paper', 'Patent', 'PatentAbstract', 'PatentClaim', 'PatentDescription', 'PatentLiteratureCitation', 'PatentNumber', 'PatentTitle', 'Pathway', 'Phase', 'Protein', 'Province', 'Reference', 'ReferenceCollection', 'Transcript','Fragment']]) As things, relationships
       with things, [x in things|id(x)] as thingsIds, relationships
       with things, ([x in relationships where not type(x) in ['INVENTOR', 'LOCATED_IN'] and id(startNode(x)) in thingsIds and id(endNode(x)) in thingsIds]) as rels
       CALL apoc.export.graphml.data(things,rels, "export.graphml", {})
       YIELD file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
       RETURN file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data;
Failed to invoke procedure `apoc.export.graphml.data`: Caused by: java.lang.RuntimeException: Export to files not enabled, please set apoc.export.file.enabled=true in your neo4j.conf
```
:(
Will fix that and rerun

**Comment by motey** [comment] 2020-07-24 07:20
~~https://cloud.connect.dzd-ev.de/s/wb5Zec7ESkZX33p~~

Edit: Based on recent data
https://cloud.connect.dzd-ev.de/s/d4pQcYNJfEM65q4

Here is the sample variant. Full scan is running again

**Comment by motey** [comment] 2020-07-24 18:58
```
call apoc.meta.graph() yield nodes, relationships
              With 
              ([x in nodes where apoc.any.properties(x).name in ['Abstract', 'AbstractCollection', 'Affiliation', 'AgeGroup', 'Author', 'AuthorCollection', 'BodyText', 'BodyTextCollection', 'Citation', 'City', 'ClinicalTrial', 'Country', 'DailyReport', 'Entity', 'ExclusionCriteria', 'Facility', 'GOTerm', 'Gene', 'GeneSymbol', 'GtexDetailedTissue', 'GtexTissue', 'InclusionCriteria', 'Location', 'Paper', 'Patent', 'PatentAbstract', 'PatentClaim', 'PatentDescription', 'PatentLiteratureCitation', 'PatentNumber', 'PatentTitle', 'Pathway', 'Phase', 'Protein', 'Province', 'Reference', 'ReferenceCollection', 'Transcript','Fragment']]) As things, relationships
              with things, [x in things|id(x)] as thingsIds, relationships
              with things, ([x in relationships where not type(x) in ['INVENTOR', 'LOCATED_IN'] and id(startNode(x)) in thingsIds and id(endNode(x)) in thingsIds]) as rels
              CALL apoc.export.graphml.data(things,rels, "export.graphml", {})
              YIELD file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
              RETURN file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data;
+---------------------------------------------------------------------------------------------------------------------------------------------------+
| file             | source                      | format    | nodes | relationships | properties | time | rows | batchSize | batches | done | data |
+---------------------------------------------------------------------------------------------------------------------------------------------------+
| "export.graphml" | "data: nodes(39), rels(53)" | "graphml" | 39    | 53            | 290        | 7    | 92   | -1        | 0       | TRUE | NULL |
+---------------------------------------------------------------------------------------------------------------------------------------------------+

1 row available after 98 ms, consumed after another 8524128 ms

``` 
Full scan variant is finished :) 

https://cloud.connect.dzd-ev.de/s/F9AbA7SZfaL92Hs

**Comment by motey** [comment] 2020-08-04 13:25
This looks shitty for me

![grafik](https://user-images.githubusercontent.com/1006417/89299281-b7fc6080-d666-11ea-8e3d-24caf020f02e.png)

Anybody who can see more?

**Comment by yGuy** [comment] 2020-08-04 14:33
As shitty as it this, this is actually "expected".  :-)
GraphML only declares the structure of the graph - any visual properties (sizes of elements, colors, even label's) are stored using various (custom) GraphML enhancements.
However the information we need is actually part of the file. 
Here is how to get a "nicer" picture from it:

After loading the file, apply a hierarchic layout via layout->hierarchical (alt-shift-h)
Then go to Edit -> Properties mapper.
Add configurations (two node configurations and one edge configuration)
Select "no" template for the configurations and add data sources for each of the configurations:
first node configuration: data source "name", map to "label text", conversion "automatic"
second node configuration: data source "type", map to "label text", conversion "automatic"
edge configuration: data source "count", map to "label text", conversion "automatic"

and/or probably rather:
edge configuration: data source "type", map to "label text", conversion "automatic"


Then press "apply or OK" and rerun the layout.

I am attaching my "properties mapper configuration" - you can just load it in the "configurations" panel and then apply it. You need to unzip it first, because otherwise I was not able to upload and attach.

This will result in this graph:

![image](https://user-images.githubusercontent.com/2486305/89305686-407eff00-d66f-11ea-9e5b-6390fd01ddd7.png)

[schema-config.zip](https://github.com/covidgraph/documentation/files/5022699/schema-config.zip)

**Closed as completed** 2020-12-07 20:57 UTC
